In [ ]:
import numpy as np
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array_1d_int = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
print("1D Array Integer:", array_1d_int)

1D Array Integer: [3 2 0 1 2]


In [ ]:
array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
random_2darray = np.random.randint(20,42, size=(4,5))
print("random_2darray:\n",random_2darray)

random_2darray:
 [[41 25 39 22 24]
 [30 20 36 31 41]
 [31 35 20 40 21]
 [34 38 24 24 40]]


In [ ]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print("Second row:", array[2,:])

Second row [21 22 23 22 22]


In [ ]:
array_1d = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
reversed_array_1d = array_1d[::-1]
print("Reversed Array:", reversed_array_1d)

Reversed Array: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array_2d = np.array([[1., 0., 0., 0.], [0., 1., 0., 0.,], [0., 0., 1., 0.,], [0., 0., 0., 1.,]])
print("4x4 Identity Matirx:\n",array_2d)

4x4 Identity Matirx:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
array_1d = np.array([3, 4, 4, 4, 4, 5, 5, 5, 5, 6])
total_sum = sum(array_1d)
average_value = np.mean(array_1d)
print("Total Sum:", total_sum)
print("Average Value:", average_value)

Total Sum: 45
Average Value: 4.5


In [ ]:
one_to_twenty = np.arange(1, 21).reshape(4,5)
print("Array from 1 to 20:", one_to_twenty)

Array from 1 to 20: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
array_odd = np.array([1, 3, 5, 7, 9])
odd_numbers = array_odd[array_odd % 2 !=0]
print("Odd Numbers:", odd_numbers)

Odd Numbers: [1 3 5 7 9]
